Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/precise32"

  config.vm.network :private_network, ip: "192.168.33.101"

  config.vm.synced_folder "./", "/vagrant", id: "vagrant-root"

  config.vm.provision :puppet do |puppet|
    	puppet.manifests_path = "puppet/manifests"
	puppet.module_path = "puppet/modules"
    	puppet.options = ['--verbose']
  end

end

